version: '3.8'
services:
  authapi:
    env_file: ".env"
    build: authapi/
    ports:
      - "8000:8000"
    networks:
      - custom_network
    restart: always
    environment:
      - ADMIN_ACCESS_TOKEN=${ADMIN_ACCESS_TOKEN}
      - CONNECTION_STRING=${CONNECTION_STRING}
    volumes:
      - ./database.db:/authapi/database.db
  chatapi:
    env_file: ".env"
    build: chatapi/
    ports:
      - "8001:8001"
    networks:
      - custom_network
    restart: always
    environment:
      - LLM_CHAT_TOKEN=${LLM_CHAT_TOKEN}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - AUTH_API=${AUTH_API}
      - LLM_API=${LLM_API}
    volumes:
      - ./database.db:/chatapi/database.db
  llmapi:
    env_file: ".env"
    build: llmapi/
    ports:
      - "8002:8002"
    networks:
      - custom_network
    restart: always
    environment:
      - LLM_CHAT_TOKEN=${LLM_CHAT_TOKEN}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - GIGACHAT_AUTH_TOKEN=${GIGACHAT_AUTH_TOKEN}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE:-GIGACHAT_API_PERS}
      - CHAT_API=${CHAT_API}
    volumes:
      - ./database.db:/llmapi/database.db
  webui:
    env_file: ".env"
    build: webui/
    depends_on:
      - authapi
    restart: always
    ports:
      - "3000:3000"
    networks:
      - custom_network
    environment:
      - VITE_API_URL=${VITE_AUTH_API}
      - VITE_CHAT_API_URL=${VITE_CHAT_API}
volumes:
  database:
networks:
  custom_network:
    name: custom_network